const STATUS_CODES = {
    BAD_REQUEST : 400,
    OK : 200,
    PERMISSION_DENIED : 403,
    INTERNAL_SERVER_ERROR : 500,
    SERVICE_UNAVAILABLE : 503,
    UNAUTHORIZED : 401,
    PAYMENT_RRQUIRED : 402,
}
module.exports = STATUS_CODES;